# Generated by Django 3.1.2 on 2020-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
