# Generated by Django 3.1.2 on 2020-10-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccess',
        ),
    ]
